#!/usr/bin/env python3
"""One command that runs The Council's whole harness.

    python3 tests/run_harness.py

It runs, in order:

1. every ``unittest`` module in ``tests/`` against real temporary packets;
2. the bundled ``skill-creator/scripts/quick_validate.py`` packaging check when
   that validator happens to be installed.

Both stages report, exit codes combine, and the process exits non-zero if either
stage fails. Nothing is written outside temporary directories, and the packaging
stage degrades to SKIPPED on a host without the validator.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import unittest
from pathlib import Path

# Keep the skill package free of generated bytecode caches.
sys.dont_write_bytecode = True

SKILL_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = SKILL_ROOT / "scripts"
TESTS_DIR = SKILL_ROOT / "tests"

QUICK_VALIDATE_CANDIDATES = (
    Path.home() / ".codex" / "skills" / ".system" / "skill-creator" / "scripts" / "quick_validate.py",
    Path("/Users/leo/.codex/skills/.system/skill-creator/scripts/quick_validate.py"),
)


def find_quick_validate() -> Path | None:
    """Return the bundled skill validator path when it is installed."""
    for candidate in QUICK_VALIDATE_CANDIDATES:
        if candidate.is_file():
            return candidate
    return None


def run_unit_tests(verbosity: int) -> tuple:
    """Discover and run every test module in ``tests/``."""
    for path in (str(SCRIPTS_DIR), str(TESTS_DIR)):
        if path not in sys.path:
            sys.path.insert(0, path)
    loader = unittest.TestLoader()
    suite = loader.discover(str(TESTS_DIR), top_level_dir=str(TESTS_DIR))
    if loader.errors:
        return False, "discovery errors:\n" + "\n".join(str(e) for e in loader.errors)
    runner = unittest.TextTestRunner(verbosity=verbosity, stream=sys.stdout)
    result = runner.run(suite)
    summary = (
        f"ran={result.testsRun} failures={len(result.failures)} "
        f"errors={len(result.errors)} skipped={len(result.skipped)}"
    )
    return result.wasSuccessful(), summary


def run_quick_validate() -> tuple:
    """Run the bundled skill validator. Returns None when it is not installed."""
    validator = find_quick_validate()
    if validator is None:
        return None, "quick_validate.py not found; packaging check skipped"
    completed = subprocess.run(
        [sys.executable, str(validator), str(SKILL_ROOT)],
        capture_output=True,
        text=True,
        check=False,
        env=dict(os.environ, PYTHONDONTWRITEBYTECODE="1"),
    )
    combined = (completed.stdout + completed.stderr).strip()
    return completed.returncode == 0, f"{validator}: {combined}"


def build_parser() -> argparse.ArgumentParser:
    """Build the harness argument parser."""
    parser = argparse.ArgumentParser(description="Run The Council skill harness.")
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="reduce unittest verbosity to one line per module",
    )
    parser.add_argument(
        "--skip-skill-validation",
        action="store_true",
        help="run only the automated tests",
    )
    return parser


def main(argv: list | None = None) -> int:
    """Run both stages and return a combined exit code."""
    args = build_parser().parse_args(argv)
    verbosity = 1 if args.quiet else 2

    print(f"== council unit tests: {TESTS_DIR}")
    tests_ok, tests_summary = run_unit_tests(verbosity)
    print(f"== council unit tests: {'PASS' if tests_ok else 'FAIL'} ({tests_summary})")

    validate_ok = None
    if not args.skip_skill_validation:
        print("== council skill packaging validation")
        validate_ok, validate_summary = run_quick_validate()
        state = "SKIPPED" if validate_ok is None else ("PASS" if validate_ok else "FAIL")
        print(f"== council skill validation: {state} ({validate_summary})")

    if not tests_ok:
        return 1
    if validate_ok is False:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
